### PR TITLE
Adding a skip parameter to ensemble2campaign and campaign2ensemble

### PR DESCRIPTION
**Pull request by wedeling**
I've added an integer `skip` parameter to `ensemble2campaign` and `campaign2ensemble`

 `campaign2ensemble`: if skip = 0, the script does the same thing as before. This is the default setting. If skip > 0, it will first clear the SWEEP directory, and only copy run directories `run_X` with `X>skip` to the SWEEP dir. In an adaptive EasyVVUQ campaign I just set skip equal to the number of already computed samples in order to avoid recomputing old samples. 

`ensemble2campign`:  if skip = 0, the script does the same thing as before. This is the default setting. If skip > 0 it does the reverse as the previous subroutine, i.e. only copy `run_X` with `X > skip` from the FabSim results directory back to the EasyVVUQ results directory.

The main purpose is to avoid copying 1000s of folders at every iteration of an large adaptive campaign, when only a few new folders are added at each iteration.

BTW: I noticed it took a long time to upload this new branch. I am worried I inadvertently uploaded a load of junk files in some folder that is not required. Any idea? Perhaps in the tmp_app foder.

### CODE REVIEW

**Comment by djgroen** [comment]
@wedeling The code changes look robust, but in the files changed listing I see a number of temporary files that you have added to the repo. Could you perhaps double check if those are necessary, and remove any unnecessary ones?

**Comment by wedeling** [comment]
Do I need any of the files .tar files in the tmp_app directory, or can I just remove those

**Comment by djgroen** [comment]
I think you can remove those and any other temporary files from the commit. Perhaps you accidentally added files to the commit? You can see the files changed here:
https://github.com/djgroen/FabSim3/pull/182/files

**Comment by wedeling** [comment]
@djgroen I think this might be ok now

**Pull request merged**
