### PR TITLE
Install requirements while installing plugin

### PR DESCRIPTION
**Pull request by arindamsaha1507**
I have extended the `install_plugin` function to install the dependencies from `requirements.txt` file of the plugin if such file is present.

### CODE REVIEW

**Comment by djgroen** [comment]
@arindamsaha1507 

Thank you for adding this functionality.

Please update the documentation to describe it for the user, and also please fix the failing tests if possible? The tests appear to have been working on previous commits after all :).

**Comment by djgroen** [comment]
Just to give you a heads up, the failed tests may be unrelated to your work, and could be caused by an issue in fabric2. Please check the test outputs carefully to see if you are able to resolve it. If you need any view from my side, just add a comment here :).

**Comment by arindamsaha1507** [comment]
@djgroen 

I have included a line in the documentation regarding the changes.

Regarding the tests, they started failing after requests module version was automatically bumped up by a bot. 

https://github.com/djgroen/FabSim3/actions/runs/5053869837

I tried fixing it... but couldn't do it myself... could you look into it?

**Comment by arabnejad** [comment]
Morning @djgroen :bowtie:
I think the problem is caused by `Invoke` package (https://github.com/fabric/fabric/issues/2263#issuecomment-1529989320)
have a look at these two issues on Fabric github

https://github.com/fabric/fabric/issues/2263
https://github.com/fabric/fabric/issues/2266

the quick fix solution would be pin the `invoke` package to `2.0.0`

**Comment by arindamsaha1507** [comment]
Finally!

All checks are successful now!

Thanks @arabnejad and @djgroen :pray:

**Pull request merged**
