### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by arabnejad**
As we discussed in  #203, I did some changes on files and folders in FabSim3 and put all FabSim3 python code files in a **separate subdirectory**, i.e., `fabsim. The repository's root directory is only used for other stuffs such as installation scripts, py tests, and all manner of other things that aren't actually part of the source code.

@djgroen : Another thing is that, if the user want to use `fab` command instead of `fabsim`, it should be called inside `FabSim3/fabsim` or `FabSim3/plugins`, I already added `fabfile.py` file in the `plugins` folder, but if you like to have access `fab` command from root directory, we can move `fabfile.py`to the repository's root directory

### CODE REVIEW

**Comment by djgroen** [comment]
Hi Hamid.

Yes, I think fabfile.py should be in FabSim3's root directory, as I think people are very used to running it from there (or from the plugin directories) :).

**Comment by djgroen** [comment]
I think that aside from that minor issue, this code is ready to be merged in.

We still have 2-3 weeks to resolve issues if they arise after the merge, and I think we'll detect them rapidly as we're all using FabSim3 extensively at the moment :).

**Comment by arabnejad** [comment]
@djgroen  
in the refactoring version, running `fab` can be called in any subdir inside `FabSim3/fabsim` or `FabSim3/plugins`
but if you like, we can easily move it to root directory

**Comment by arabnejad** [comment]
@djgroen 

I moved the `fabfile.py` to the root directory and also fixed its path in `/fabsim/bin/fabsim` executable file

**Pull request merged**
